
from __future__ import annotations
from typing import Protocol, Tuple

class KEM(Protocol):
    name: str
    def keygen(self) -> Tuple[bytes, bytes]: ...
    def encapsulate(self, public_key: bytes) -> Tuple[bytes, bytes]: ...
    def decapsulate(self, secret_key: bytes, ciphertext: bytes) -> bytes: ...

class Signature(Protocol):
    name: str
    def keygen(self) -> Tuple[bytes, bytes]: ...
    def sign(self, secret_key: bytes, message: bytes) -> bytes: ...
    def verify(self, public_key: bytes, message: bytes, signature: bytes) -> bool: ...
